/**
 * Files of the game page embedded into the single binary, keyed by URL path
 * (e.g. "/index.html", "/assets/index-abc.js"). Values are paths readable with
 * `fs` inside the binary's virtual file system ("/$bunfs/...").
 *
 * The manifest (generated by scripts/gen-assets.ts, not checked in) is only
 * loaded inside a compiled binary: Bun's runtime honours
 * `with { type: "file" }` for images but would execute the page's .js bundle.
 * Outside the binary — development, tests — the map is empty and Vite serves
 * the page.
 *
 * require() instead of import: tsc does not have to understand the import
 * attributes of the generated file, and it need not exist; `bun build` still
 * bundles it.
 */
// Bun.main is the entry module's path at run time — inside a compiled binary
// it lies in the virtual file system (__dirname would be inlined at build time)
const entry = (globalThis as { Bun?: { main: string } }).Bun?.main ?? '';
const isCompiledBinary = entry.startsWith('/$bunfs/') || entry.startsWith('B:\\~BUN\\');

export const assets: Record<string, string> = isCompiledBinary
  ? // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('./assets.gen').assets
  : {};
