/**
 * Generates src/embedded/assets.gen.ts: one `with { type: "file" }` import per
 * file of the frontend build (game-web/dist), so `bun build --compile` embeds
 * the game page into the single binary.
 *
 * game-web/public/assets is a symlink to the repo's assets/ folder, which also
 * holds the artwork sources (raw/, *.af, the scanned manual — ~180 MB). Only
 * what the game loads is embedded; the size limit catches anything new that
 * slips through.
 *
 * Without a frontend build an empty manifest is written — the server then
 * only serves the API.
 *
 * Usage: bun scripts/gen-assets.ts
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, relative, sep } from 'path';

const MAX_TOTAL_BYTES = 150 * 1024 * 1024;

/** URL paths (relative to dist, "/"-separated) that are never embedded. */
const EXCLUDE: RegExp[] = [
  /^assets\/raw\//,
  /\.af$/i,
  /\.md$/i,
  /\.txt$/i,
  /\.map$/i,
  /^assets\/Anleitung\.jpg$/,
  /^test-images\.html$/,
];

const backendDir = join(import.meta.dir, '..');
const distDir = join(backendDir, '..', 'game-web', 'dist');
const outDir = join(backendDir, 'src', 'embedded');
const outFile = join(outDir, 'assets.gen.ts');

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap(name => {
    if (name.startsWith('.')) return []; // .DS_Store & co.
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const toUrl = (file: string) => relative(distDir, file).split(sep).join('/');

const files = existsSync(distDir)
  ? walk(distDir).filter(file => !EXCLUDE.some(re => re.test(toUrl(file)))).sort()
  : [];

const totalBytes = files.reduce((sum, file) => sum + statSync(file).size, 0);
const mb = (totalBytes / 1024 / 1024).toFixed(1);
if (totalBytes > MAX_TOTAL_BYTES) {
  console.error(`assets.gen.ts: ${files.length} files, ${mb} MB — over the ${MAX_TOTAL_BYTES / 1024 / 1024} MB limit.`);
  console.error('Exclude source artwork in backend/scripts/gen-assets.ts instead of embedding it.');
  process.exit(1);
}

const lines = [
  '// Generated by scripts/gen-assets.ts — do not edit, not checked in.',
  '// Maps URL paths of the game page to files embedded in the binary.',
  '/* eslint-disable */',
];
const entries: string[] = [];
files.forEach((file, i) => {
  const importPath = relative(outDir, file).split(sep).join('/');
  lines.push(`import f${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify('/' + toUrl(file))}: f${i},`);
});
lines.push('', 'export const assets: Record<string, string> = {', ...entries, '};', '');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'));
console.log(
  `assets.gen.ts: ${files.length} files, ${mb} MB${files.length === 0 ? ' (no frontend build found)' : ''}`,
);
